### PR TITLE
Use forked react-tree-walker

### PR DESCRIPTION
**Pull request by dvkndn**
While waiting for: https://github.com/ctrlplusb/react-tree-walker/pull/23/files

### CODE REVIEW

**Comment by daohoangson** [comment]
Your PR may need some re-factor to encourage the maintainer to merge it.

(1) Probably squash all commits to avoid messing with the project history.

(2) These lines:

```js
const child = getChildren()
const theChild = getValidChild(child)
```

...probably should be:

```js
const child = getValidChild(getChildren())
```

...to avoid changing the child -> theChild unnecessary in the following lines. Maybe rename the `getValidChild` to `renderChildren` or something? Drop the comments or at least move the links into commit message, people can run `git blame` for that.

(3) I'm not sure your PR should include the built assets, probably need to confirm with the author for that.

Anyway, I would love to have this PR too ctrlplusb/react-tree-walker#20... Maybe I will wait for him to merge and publish new version.

**Comment by dvkndn** [comment]
I see, thank you, will fix soon <3

**Comment by daohoangson** [comment]
Looks great @dvkndn, hope ctrlplusb/react-tree-walker#23 will be merged soon.

**Comment by daohoangson** [comment]
Huh? The PR for `react-tree-walker` hasn't been merged yet eh?

**Comment by dvkndn** [comment]
@daohoangson no, the PR is not merged yet.

Still, we should not use that directly, because the branch only has changes in the source code, not in the bundled code (ie: `commonjs/index.js` is still the old one).

In other to use that branch from package.json directly, we must build it, but that makes the branch polluted and could not be merged into upstream.

**Comment by daohoangson** [comment]
Ah I see.

**Pull request closed without merging**
